import { internalMutation } from "./_generated/server";
import type { MutationCtx } from "./_generated/server";
import type { Id, TableNames } from "./_generated/dataModel";

// Shared neutral blur placeholder for seeded images. Real per-image blur data
// will be generated by the future admin upload pipeline.
const BLUR_DATA_URL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgAAIAAAUAAen63NgAAAAASUVORK5CYII=";

const unsplash = (photoId: string) =>
  `https://images.unsplash.com/${photoId}?w=1600&h=1200&fit=crop&q=80`;

// Plain hardcoded dummy data for seeding — no faker dependency, kept lean for performance.
const dummyPhotoCaptions = [
  "Quiet moment between the formalities",
  "Golden hour by the entrance",
  "Laughter during the speeches",
  "Details worth remembering",
  "Walking in together",
  "A candid glance across the room",
];

const dummyEnquiries: Array<{
  name: string;
  phone: string;
  email?: string;
  message: string;
}> = [
  {
    name: "Akosua Mensah",
    phone: "+233241112233",
    email: "akosua.mensah@example.com",
    message: "Hi, we're getting married in November and would love a quote for full-day coverage.",
  },
  {
    name: "Kwabena Owusu",
    phone: "+233201234567",
    message: "Looking for a headshot session for our team of six before the end of the month.",
  },
  {
    name: "Efua Asante",
    phone: "+233551239876",
    email: "efua.asante@example.com",
    message: "Do you travel outside Koforidua for family portrait sessions? We're based in Accra.",
  },
  {
    name: "Yaw Boateng",
    phone: "+233271002030",
    message: "We're hosting a graduation party next month and would like candid event coverage.",
  },
  {
    name: "Adwoa Darko",
    phone: "+233244556677",
    email: "adwoa.darko@example.com",
    message: "Interested in a brand shoot for our bakery's new product line — could we get a custom quote?",
  },
  {
    name: "Kojo Asiedu",
    phone: "+233207894561",
    message: "Could you share availability for a half-day engagement shoot in early December?",
  },
];

type CategoryKey = "Weddings" | "Portraits" | "Events" | "Studio" | "Commercial";

const categoryPhotoIds: Record<CategoryKey, string[]> = {
  Weddings: [
    "photo-1520854221256-17451cc331bf",
    "photo-1532712938310-34cb3982ef74",
    "photo-1537633552985-df8429e8048b",
    "photo-1519741196428-6a2175fa2557",
    "photo-1604017011826-d3b4c23f8914",
    "photo-1623783356340-95375aac85ce",
  ],
  Portraits: [
    "photo-1506863530036-1efeddceb993",
    "photo-1544005313-94ddf0286df2",
    "photo-1502823403499-6ccfcf4fb453",
    "photo-1544124094-8aea0374da93",
    "photo-1536766768598-e09213fdcf22",
    "photo-1508184964240-ee96bb9677a7",
  ],
  Events: [
    "photo-1531058020387-3be344556be6",
    "photo-1511795409834-ef04bbd61622",
    "photo-1501281668745-f7f57925c3b4",
    "photo-1614607653708-0777e6d003b8",
    "photo-1612389930565-6975454dc7cc",
    "photo-1508657794088-375f2f60c581",
  ],
  Studio: [
    "photo-1471341971476-ae15ff5dd4ea",
    "photo-1527011046414-4781f1f94f8c",
    "photo-1617463874381-85b513b3e991",
    "photo-1554941829-202a0b2403b8",
    "photo-1611093791822-15086535830b",
    "photo-1598006640672-f0cc33c40702",
  ],
  Commercial: [
    "photo-1590486803833-1c5dc8ddd4c8",
    "photo-1554866585-cd94860890b7",
    "photo-1542992933-ce75d0187ec1",
    "photo-1486149370945-b0e59dc9485b",
    "photo-1604759695540-3012f9682c28",
    "photo-1578305871734-698fd02cd6f9",
  ],
};

function image(photoId: string, alt: string) {
  return {
    url: unsplash(photoId),
    width: 1600,
    height: 1200,
    blurDataURL: BLUR_DATA_URL,
    alt,
  };
}

async function clearTable(ctx: MutationCtx, table: TableNames) {
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const batch = await ctx.db.query(table).take(100);
    if (batch.length === 0) return;
    for (const doc of batch) {
      await ctx.db.delete(doc._id);
    }
  }
}

const albumSeeds: Array<{
  title: string;
  slug: string;
  category: CategoryKey;
  description: string;
  shootDate: string;
  featured: boolean;
}> = [
  {
    title: "Ama & Kwame's Garden Wedding",
    slug: "ama-and-kwame-garden-wedding",
    category: "Weddings",
    description:
      "An intimate garden ceremony in Koforidua followed by an evening of dancing, speeches, and good food with family from across the Eastern Region.",
    shootDate: "2026-02-14",
    featured: true,
  },
  {
    title: "Abena & Yaw: A Koforidua Celebration",
    slug: "abena-and-yaw-koforidua-celebration",
    category: "Weddings",
    description:
      "Traditional engagement and white wedding coverage spanning a full weekend, from the morning preparations to the last dance.",
    shootDate: "2025-11-22",
    featured: false,
  },
  {
    title: "Graduation Portraits, UMaT 2026",
    slug: "graduation-portraits-umat-2026",
    category: "Portraits",
    description:
      "On-campus graduation portrait sessions for the UMaT class of 2026, mixing formal gown shots with candid celebration moments.",
    shootDate: "2026-04-10",
    featured: true,
  },
  {
    title: "Family Portrait Sessions",
    slug: "family-portrait-sessions",
    category: "Portraits",
    description:
      "A weekend of relaxed, on-location family portrait sessions around Koforidua, built around natural light and easy poses.",
    shootDate: "2025-12-05",
    featured: false,
  },
  {
    title: "Koforidua Tech & Innovation Summit",
    slug: "koforidua-tech-innovation-summit",
    category: "Events",
    description:
      "Full-day conference coverage: keynote talks, panel discussions, networking breaks, and the closing awards ceremony.",
    shootDate: "2026-03-18",
    featured: true,
  },
  {
    title: "New Year's Eve Gala 2026",
    slug: "new-years-eve-gala-2026",
    category: "Events",
    description:
      "Coverage of a black-tie countdown gala, from the red carpet arrivals to the midnight toast.",
    shootDate: "2025-12-31",
    featured: false,
  },
  {
    title: "Studio Headshots, Spring Batch",
    slug: "studio-headshots-spring-batch",
    category: "Studio",
    description:
      "Clean, consistent corporate headshots shot against a seamless backdrop for a batch of professionals updating their profiles.",
    shootDate: "2026-01-20",
    featured: false,
  },
  {
    title: "Creative Portrait Studio Session",
    slug: "creative-portrait-studio-session",
    category: "Studio",
    description:
      "An experimental session exploring colour gels, hard shadows, and bold composition inside the studio.",
    shootDate: "2025-10-08",
    featured: true,
  },
  {
    title: "Bespoke Bakery, Brand Campaign",
    slug: "bespoke-bakery-brand-campaign",
    category: "Commercial",
    description:
      "Product and lifestyle imagery for a Koforidua bakery's seasonal menu launch and social media campaign.",
    shootDate: "2026-05-02",
    featured: false,
  },
  {
    title: "Kofi's Furniture Showroom",
    slug: "kofis-furniture-showroom",
    category: "Commercial",
    description:
      "Catalogue-style photography of a furniture showroom's new collection for print and web use.",
    shootDate: "2025-09-14",
    featured: false,
  },
];

const packageSeeds = [
  {
    name: "Essential Wedding",
    category: "Weddings",
    price: 3500,
    priceType: "from" as const,
    duration: "Up to 6 hours",
    description:
      "Ceremony and reception coverage with a same-week sneak peek gallery, perfect for smaller celebrations.",
    features: [
      "6 hours of coverage",
      "1 photographer",
      "200+ edited digital photos",
      "Private online gallery",
    ],
    popular: false,
  },
  {
    name: "Signature Wedding",
    category: "Weddings",
    price: 6500,
    priceType: "from" as const,
    duration: "Full day coverage",
    description:
      "Full-day storytelling from morning preparations to the last dance, with a second photographer and a printed album.",
    features: [
      "Up to 10 hours of coverage",
      "2 photographers",
      "400+ edited digital photos",
      "Printed wedding album",
      "Engagement mini-session",
    ],
    popular: true,
  },
  {
    name: "Solo Portrait Session",
    category: "Portraits",
    price: 450,
    priceType: "fixed" as const,
    duration: "45 minutes",
    description:
      "A relaxed studio or on-location session for individual portraits, headshots, or personal branding photos.",
    features: ["45 minute session", "2 outfit changes", "20 edited digital photos"],
    popular: false,
  },
  {
    name: "Family Portrait Session",
    category: "Portraits",
    price: 750,
    priceType: "fixed" as const,
    duration: "1 hour",
    description:
      "On-location family portraits built around natural light, easy poses, and genuine moments together.",
    features: [
      "1 hour session",
      "Up to 6 people",
      "30 edited digital photos",
      "Print release included",
    ],
    popular: true,
  },
  {
    name: "Half-Day Event Coverage",
    category: "Events",
    price: 1800,
    priceType: "from" as const,
    duration: "Up to 4 hours",
    description:
      "Candid coverage for parties, launches, and milestones, delivered as a fast-turnaround edited gallery.",
    features: ["4 hours of coverage", "1 photographer", "150+ edited digital photos"],
    popular: false,
  },
  {
    name: "Full-Day Event Coverage",
    category: "Events",
    price: 3200,
    priceType: "from" as const,
    duration: "Up to 8 hours",
    description:
      "End-to-end coverage for conferences, galas, and larger events, including speaker and audience moments.",
    features: [
      "8 hours of coverage",
      "2 photographers",
      "300+ edited digital photos",
      "48 hour highlight gallery",
    ],
    popular: false,
  },
  {
    name: "Professional Headshot",
    category: "Studio",
    price: 350,
    priceType: "fixed" as const,
    duration: "30 minutes",
    description:
      "Clean, consistent headshots against a seamless backdrop, ideal for resumes, websites, and team pages.",
    features: ["30 minute session", "1 backdrop colour", "5 edited digital photos"],
    popular: false,
  },
  {
    name: "Studio Creative Session",
    category: "Studio",
    price: 600,
    priceType: "fixed" as const,
    duration: "1.5 hours",
    description:
      "An experimental studio session with creative lighting, colour, and concepts tailored to your vision.",
    features: ["90 minute session", "Custom lighting setup", "15 edited digital photos"],
    popular: false,
  },
  {
    name: "Brand & Product Shoot",
    category: "Commercial",
    price: 0,
    priceType: "custom" as const,
    duration: "Scoped to your campaign",
    description:
      "Product, lifestyle, and campaign imagery scoped to your brand's needs. Get in touch for a tailored quote.",
    features: ["Custom shot list", "Studio or on-location", "Licensed for commercial use"],
    popular: false,
  },
  {
    name: "Small Business Starter",
    category: "Commercial",
    price: 1200,
    priceType: "from" as const,
    duration: "Half-day session",
    description:
      "A focused half-day session covering your space, products, and team, ready for your website and social pages.",
    features: ["Half-day session", "25 edited digital photos", "Web-ready exports"],
    popular: true,
  },
];

export const run = internalMutation({
  args: {},
  handler: async (ctx) => {
    await clearTable(ctx, "enquiries");
    await clearTable(ctx, "photos");
    await clearTable(ctx, "albums");
    await clearTable(ctx, "packages");
    await clearTable(ctx, "siteSettings");

    await ctx.db.insert("siteSettings", {
      hero: {
        images: [
          image(
            categoryPhotoIds.Weddings[0],
            "Bride and groom holding hands at sunset in Koforidua"
          ),
          image(
            categoryPhotoIds.Portraits[0],
            "Natural light portrait session in Koforidua"
          ),
          image(
            categoryPhotoIds.Events[0],
            "Guests celebrating together at an evening event"
          ),
          image(
            categoryPhotoIds.Studio[0],
            "Professional studio portrait lighting setup"
          ),
          image(
            categoryPhotoIds.Commercial[0],
            "Product photography for a local Koforidua brand"
          ),
        ],
        headline: "Capturing Koforidua's stories, one frame at a time",
        subtext:
          "Smak Photography is a Koforidua-based studio specializing in weddings, portraits, and events across Ghana.",
      },
      aboutSnippet:
        "Founded in Koforidua, Smak Photography blends technical precision with genuine warmth, turning everyday moments into images you will want to keep for a lifetime.",
      aboutFull:
        "Smak Photography started in Koforidua with a simple idea: photography should feel like a conversation, not a performance. What began as weekend portrait sessions for friends has grown into a full studio covering weddings, portraits, events, and commercial work across the Eastern Region and beyond.\n\nWe believe the best images come from people feeling like themselves, so every session starts with a conversation about what matters to you, not a checklist of poses. From the first phone call to the final gallery, we aim to make the experience as enjoyable as the photographs themselves.\n\nToday, the studio works with couples, families, organisations, and brands who want images that feel honest, warm, and true to who they are. Wherever you are in Ghana, we would love to help tell your story.",
      aboutImage: image(
        categoryPhotoIds.Studio[2],
        "Smak Photography photographer at work in the studio"
      ),
      stats: [
        { value: "8+", label: "Years in business" },
        { value: "500+", label: "Happy clients" },
        { value: "150+", label: "Weddings captured" },
        { value: "10k+", label: "Photos delivered" },
      ],
      phone: "+233 24 123 4567",
      whatsapp: "+233241234567",
      email: "hello@smakphotography.com",
      address: "123 Stadium Road, Koforidua, Eastern Region, Ghana",
      hours: "Monday – Saturday: 9:00 AM – 6:00 PM\nSunday: By appointment only",
      mapsUrl: "https://maps.google.com/maps?q=Koforidua%2C+Ghana&output=embed",
      socials: [
        { platform: "Instagram", url: "https://instagram.com/smakphotography" },
        { platform: "TikTok", url: "https://tiktok.com/@smakphotography" },
        { platform: "Snapchat", url: "https://snapchat.com/add/smakphotography" },
        { platform: "YouTube", url: "https://youtube.com/@smakphotography" },
      ],
    });

    const packageIds: Array<{ id: Id<"packages">; name: string }> = [];
    for (let i = 0; i < packageSeeds.length; i++) {
      const seed = packageSeeds[i];
      const id = await ctx.db.insert("packages", {
        ...seed,
        currency: "GHS",
        active: true,
        order: i,
      });
      packageIds.push({ id, name: seed.name });
    }

    for (let i = 0; i < albumSeeds.length; i++) {
      const seed = albumSeeds[i];
      const photoIds = categoryPhotoIds[seed.category].slice(
        (i % 2) * 3,
        (i % 2) * 3 + 3
      );

      const albumId = await ctx.db.insert("albums", {
        title: seed.title,
        slug: seed.slug,
        category: seed.category,
        description: seed.description,
        cover: image(photoIds[0], seed.title),
        photoCount: photoIds.length,
        shootDate: seed.shootDate,
        published: true,
        featured: seed.featured,
        order: i,
      });

      for (let p = 0; p < photoIds.length; p++) {
        await ctx.db.insert("photos", {
          albumId,
          image: image(photoIds[p], `${seed.title} — photo ${p + 1}`),
          caption: p === 0 ? undefined : dummyPhotoCaptions[(i + p) % dummyPhotoCaptions.length],
          order: p,
        });
      }
    }

    const statuses = ["new", "contacted", "booked", "closed"] as const;
    const sources = ["services", "contact"] as const;
    for (let i = 0; i < 6; i++) {
      const source = sources[i % sources.length];
      const withPackage = source === "services" && i % 2 === 0;
      const pkg = withPackage ? packageIds[i % packageIds.length] : null;

      const enquiry = dummyEnquiries[i % dummyEnquiries.length];

      await ctx.db.insert("enquiries", {
        name: enquiry.name,
        phone: enquiry.phone,
        email: enquiry.email,
        message: enquiry.message,
        packageId: pkg?.id,
        packageName: pkg?.name,
        source,
        status: statuses[i % statuses.length],
      });
    }

    return null;
  },
});
